lions_den/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('zoo_auth.urls')),
    path('zoos/', include('zoo_editor.urls'), name='zoos'),
    path('admin/', admin.site.urls),
    path('tickets/', include('ticket_system.urls'), name='tickets')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lions_den/ticket_system/urls.py
from django.urls import path

from .views import TicketListView, TicketView

urlpatterns = [
	path('', TicketListView.as_view(), name='ticket_list'),
	path('browse/<int:pk>', TicketView.as_view(), name='ticket_page')
]

lions_den/ticket_system/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


class TrackedFieldsModel(models.Model):
	class Meta:
		abstract = True
	
	def save(self, *args, **kwargs):
		action_ticket = self if type(self) == Ticket else self.ticket
		ticket_changes = []
		if self.pk: # pre-existing model instance
			old_instance = type(self).objects.get(pk=self.pk)
			
			super().save(*args, **kwargs)
			
			ticket_action = TicketAction(ticket=action_ticket, target=self, user=action_ticket.last_updater, type=TicketAction.Type.EDIT)
			for tracked_field in self.tracked_fields:
				old_value, new_value = getattr(old_instance, tracked_field.name), getattr(self, tracked_field.name)
				if old_value != new_value:
					ticket_changes.append(TicketChange(action=ticket_action, field=tracked_field.name, old_value=old_value, new_value=new_value))
		else: # new model instance
			super().save(*args, **kwargs)
			ticket_action = TicketAction(ticket=action_ticket, target=self, user=action_ticket.last_updater, type=TicketAction.Type.CREATE)
			for tracked_field in self.tracked_fields:
				new_value = getattr(self, tracked_field.name)
				if new_value:
					ticket_changes.append(TicketChange(action=ticket_action, field=tracked_field.name, new_value=new_value))
		
		if ticket_changes:
			ticket_action.save()
			for ticket_change in ticket_changes:
				ticket_change.save()
			ticket_action.trigger_notifications()


class Ticket(TrackedFieldsModel):
	class App(models.TextChoices):
		ZOOVERSE = 'ZV', _('Zooverse')
		LIONS_DEN = 'LD', _("Lion's Den")
	
	class Status(models.TextChoices):
		UNASSIGNED = 'U', _('Unassigned')
		IN_ANALYSIS = 'A', _('In Analysis')
		IN_DEVELOPMENT = 'D', _('In Development')
		CANCELLED = 'CA', _('Cancelled')
		REJECTED = 'R', _('Rejected')
		COMPLETED = 'CO', _('Completed')
		
		@classmethod
		def is_open(cls, status_str):
			return status_str not in (cls.CANCELLED, cls.REJECTED, cls.COMPLETED)
	
	class Type(models.TextChoices):
		BUG = 'B', _('Bug')
		FEATURE = 'F', _('Feature Request')
		IMPROVEMENT = 'I', _('Improvement Request')
		MAINTENANCE = 'M', _('Maintenance')
	
	class Priority(models.IntegerChoices):
		TRIVIAL = 0, _('Trivial')
		LOW = 1, _('Low')
		MEDIUM = 2, _('Medium')
		HIGH = 3, _('High')
		CRITICAL = 4, _('Critical')
	
	id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=128, verbose_name='Title')
	description = models.TextField(verbose_name='Description')
	
	app = models.CharField(max_length=2, choices=App.choices, blank=False, verbose_name='App')
	status = models.CharField(max_length=2, choices=Status.choices, default=Status.UNASSIGNED, blank=False, verbose_name='Status')
	type = models.CharField(max_length=2, choices=Type.choices, blank=False, verbose_name='Type')
	priority = models.IntegerField(choices=Priority.choices, blank=False, verbose_name='Priority')
	
	reporter = models.ForeignKey(get_user_model(), related_name='reported_tickets', on_delete=models.PROTECT, blank=True, null=True, default=None, verbose_name='Reporter')
	assignee = models.ForeignKey(get_user_model(), related_name='assigned_tickets', on_delete=models.PROTECT, blank=True, null=True, default=None, verbose_name='Assignee')
	last_updater = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, blank=True, null=True, default=None, verbose_name='Last Updater')
	watchers = models.ManyToManyField(get_user_model(), related_name='watched_tickets', blank=True, default=None)
	
	created_date = models.DateTimeField(auto_now_add=True)
	last_updated_date = models.DateTimeField(auto_now=True)
	closed_date = models.DateTimeField(blank=True, null=True)
	
	# Define the fields whose changes are tracked
	tracked_fields = [title, description, app, status, type, priority, assignee]
	
	def __str__(self):
		return f'#{self.id} - {self.title}'
	
	def is_open(self):
		return self.Status.is_open(self.status)
	
	def get_status_colour(self):
		if self.status == self.Status.UNASSIGNED:
			return'var(--info)'
		elif self.status == self.Status.IN_ANALYSIS:
			return 'var(--cyan)'
		elif self.status == self.Status.IN_DEVELOPMENT:
			return 'var(--primary)'
		elif self.status in (self.Status.CANCELLED, self.Status.REJECTED):
			return 'var(--danger)'
		elif self.status == self.Status.COMPLETED:
			return 'var(--success)'


class Comment(TrackedFieldsModel):
	id = models.AutoField(primary_key=True)
	ticket = models.ForeignKey(Ticket, related_name='comments', on_delete=models.CASCADE)
	creator = models.ForeignKey(get_user_model(), related_name='comments', on_delete=models.PROTECT)
	text = models.TextField(verbose_name='Contents')
	added_date = models.DateTimeField(auto_now_add=True)
	last_updated_date = models.DateTimeField(auto_now=True)

	tracked_fields = [text]

	def __str__(self):
		return self.text
	
	def is_edited(self):
		return self.added_date != self.last_updated_date


class TicketAttachment(models.Model):
	ticket = models.ForeignKey(Ticket, related_name='attachments', on_delete=models.CASCADE)
	comment = models.ForeignKey(Comment, related_name='attachments', on_delete=models.CASCADE)
	name = models.CharField(max_length=128, blank=False)
	file = models.FileField(blank=False)
	uploader = models.ForeignKey(get_user_model(), related_name='attachments', on_delete=models.PROTECT)
	uploaded_date = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name


class TicketAction(models.Model):
	class Type(models.TextChoices):
		CREATE = 'CREATE', _('created')
		EDIT = 'EDIT', _('edited')
	
	ticket = models.ForeignKey(Ticket, related_name='actions', on_delete=models.CASCADE)
	user = models.ForeignKey(get_user_model(), related_name='ticket_actions', on_delete=models.PROTECT)
	timestamp = models.DateTimeField(auto_now_add=True)
	type = models.CharField(max_length=6, choices=Type.choices, blank=False)
	
	# Model that is the target of the change, e.g. Ticket, Comment, etc.
	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	target = GenericForeignKey('content_type', 'object_id')
	
	def __str__(self):
		return f'{self.ticket}: {self.user} {self._get_predicate_str(as_html=False)}'
	
	def is_creation(self):
		return self.type == self.Type.CREATE
	
	def _get_predicate_str(self, as_html=False):
		predicate_str = ''
		target_str = f'<b>{self.target}</b>' if as_html else f'{self.target}'
		if type(self.target) == Ticket:
			if self.type == self.Type.CREATE:
				predicate_str = f'created {target_str}'
			elif self.type == self.Type.EDIT:
				predicate_str = f'made changes to {target_str}'
		elif type(self.target) == Comment:
			if self.type == self.Type.CREATE:
				predicate_str = 'added a comment'
				num_attachments = len(self.target.attachments.all())
				if num_attachments == 1:
					predicate_str += ' with an attachment'
				elif num_attachments > 1:
					predicate_str += f' with {num_attachments} attachments'
			elif self.type == self.Type.EDIT:
				predicate_str = 'edited a comment'
		return predicate_str
	
	def as_html(self):
		return f'<b>{self.user}</b> {self._get_predicate_str(as_html=True)}'
	
	def trigger_notifications(self):
		# In-app notifications
		for user in self.ticket.watchers.all():
			if user != self.user and user.wants_app_notifications(): # users shouldn't be notified of their own actions
				TicketActionNotification(
					user=user,
					action=self
				).save()

		# Email notifications
		users_to_notify = self.ticket.watchers.exclude(id=self.user.id).all() # users shouldn't be notified of their own actions
		get_user_model().notify_users(
			users=users_to_notify,
			subject=str(self),
			html_message=render_to_string(
				template_name='ticket_system/emails/notification.html',
				context={'action': self}
			)
		)


class TicketChange(models.Model):
	action = models.ForeignKey(TicketAction, related_name='changes', on_delete=models.CASCADE)
	field = models.CharField(max_length=32, blank=False)
	old_value = models.TextField(blank=True, null=True)
	new_value = models.TextField(blank=True, null=True)
	
	def _get_field(self):
		return getattr(type(self.action.target), self.field).field
	
	def get_field_name(self):
		return self._get_field().verbose_name
	
	def _get_value_display(self, stored_value):
		field = self._get_field()
		if field.choices:
			for choice_key, choice_value in field.choices:
				if str(choice_key) == str(stored_value):
					return choice_value
		return stored_value
	
	def get_old_value_display(self):
		return self._get_value_display(self.old_value)
	
	def get_new_value_display(self):
		return self._get_value_display(self.new_value)


class TicketActionNotification(models.Model):
	user = models.ForeignKey(get_user_model(), related_name='ticket_notifications', on_delete=models.CASCADE)
	action = models.ForeignKey(TicketAction, related_name='user_notifications', on_delete=models.CASCADE)
	
	def as_html(self):
		return self.action.as_html()
	
	def timestamp(self):
		return self.action.timestamp
	
	def url(self):
		return reverse_lazy('ticket_page', kwargs={'pk': self.action.ticket.id})

lions_den/ticket_system/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils import timezone

# noinspection PyUnresolvedReferences
from zoo_auth.models import ZooUser

from .models import Ticket, Comment, TicketAttachment


class BaseTicketForm(forms.ModelForm):
	def save(self, updater, commit=True):
		self.instance.last_updater = updater
		super().save(commit)


class TicketForm(BaseTicketForm):
	class Meta:
		model = Ticket
		fields = ('app', 'title', 'type', 'priority', 'description')
	
	def save(self, updater, commit=True):
		if not self.instance.pk: # new ticket
			self.instance.reporter = updater
			super().save(updater, commit)
			self.instance.watchers.add(updater)
			self.instance.save()
		else:
			super().save(updater, commit)


class TicketAssigneeForm(BaseTicketForm):
	class Meta:
		model = Ticket
		fields = ('assignee',)
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['assignee'] = forms.ModelChoiceField(queryset=get_user_model().objects.filter(is_staff=True))
	
	def save(self, updater, commit=True):
		super().save(updater=updater, commit=False)
		if self.instance.status == Ticket.Status.UNASSIGNED and self.instance.assignee is not None:
			self.instance.status = Ticket.Status.IN_ANALYSIS
		super().save(updater=updater, commit=commit)


class TicketStatusForm(BaseTicketForm):
	class Meta:
		model = Ticket
		fields = ('status',)
	
	def save(self, updater, commit=True):
		super().save(updater=updater, commit=False)
		if self.instance.is_open() != Ticket.Status.is_open(self.initial['status']):
			self.instance.closed_date = timezone.now() if not self.instance.is_open() else None
		super().save(updater=updater, commit=commit)


class CommentForm(forms.ModelForm):
	id = forms.CharField(widget=forms.HiddenInput, required=False)
	class Meta:
		model = Comment
		fields = ('id', 'text')
		widgets = {
			'text': forms.Textarea(attrs={'rows': 3}),
		}
		labels = {
			'text': 'Comment'
		}
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		if self.data and self.data.get('id'): # to allow for editing comments
			self.instance = self._meta.model.objects.filter(id=self.data.get('id')).get()
			
	def save(self, ticket=None, creator=None, commit=True):
		if ticket:
			self.instance.ticket = ticket
		if creator:
			self.instance.creator = creator
		
		# Add comment creator as ticket watcher
		self.instance.ticket.watchers.add(self.instance.creator)
		
		# Update last updater and last updated date on host ticket
		self.instance.ticket.last_updater = self.instance.creator
		self.instance.ticket.save()
		
		# Save last to ensure ticket.last_updater is correct for notifications
		super().save(commit)


class TicketAttachmentForm(forms.ModelForm):
	class Meta:
		model = TicketAttachment
		fields = ('file',)
		labels = {'file': 'Attachment'}
	
	def save(self, ticket, comment, uploader, commit=True):
		self.instance.name = self.instance.file.file.name
		self.instance.ticket = ticket
		self.instance.comment = comment
		self.instance.uploader = uploader
		super().save(commit)

lions_den/templates/ticket_system/base.html
{% extends 'base.html' %}

{% block extra_navbar_items %}
	{% include 'utils/buttons/plus.html' with css_class='navbar-image mr-3' stroke='var(--colorBackground)' onclick="getModal('modal_new_ticket')" %}
{% endblock %}

lions_den/templates/ticket_system/notification_email.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
		<title></title>
		
		<style type="text/css">
		</style>
	</head>
	<body style="margin:0; padding:0; background-color:#F2F2F2;">
		<center>
			<table width="100%" border="1" cellpadding="3" cellspacing="0" bgcolor="#F2F2F2">
				<tr bgcolor="#68b733">
					<td align="center" valign="top"><strong>Field</strong></td>
					{% if edit_instance %}
						<td align="center" valign="top"><strong>Old value</strong></td>
						<td align="center" valign="top"><strong>New value</strong></td>
					{% else %}
						<td align="center" valign="top"><strong>Value</strong></td>
					{% endif %}
				</tr>
				{% for field, field_changes in context.items %}
					<tr>
						<td align="center" valign="top">
							<strong>{{ field }}</strong>
						</td>
						{% if edit_instance %}
							<td align="center" valign="top">
								{{ field_changes.old_value }}
							</td>
						{% endif %}
						<td align="center" valign="top">
							{{ field_changes.new_value }}
						</td>
					</tr>
				{% endfor %}
			</table>
		</center>
	</body>
</html>

lions_den/templates/ticket_system/ticket.html
{% extends 'ticket_system/base.html' %}
{% load lions_den_tags %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="row shadow-lg">
		<div class="col-9 border">
			<div class="my-2">
				<div class="float-left"><h2>{{ ticket }}</h2></div>
				<div class="float-right">
					<div class="row">
						<div class="col px-0 mx-1">
							{% if request.user == ticket.reporter or request.user.is_staff %}
								<div id="EditTicketDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									{% include 'utils/buttons/edit.html' with css_class='edit-ticket-button' height=20 width=20 tooltip_text='Edit ticket' tooltip_placement='top' %}
								</div>
								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
									<a class="dropdown-item" href="#" onclick="getModal('modal_edit_ticket')">Edit Ticket</a>
									<a class="dropdown-item" href="#" onclick="getModal('modal_ticket_status')">Edit Status</a>
								</div>
							{% endif %}
						</div>
						<div class="col px-0 mx-3">
							{% if user_is_watcher %}
								{% include 'utils/buttons/eye.html' with stroke='var(--colorPrimary)' height=20 width=20 tooltip_text='Stop watching' tooltip_placement='top' onclick='setUserWatcherStatus(false)' id='add_as_watcher_btn' %}
							{% else %}
								{% include 'utils/buttons/eye.html' with stroke='var(--colorForeground)' height=20 width=20 tooltip_text='Start watching' tooltip_placement='top' onclick='setUserWatcherStatus(true)' id='add_as_watcher_btn' %}
							{% endif %}
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
				
				<h6 style="color:var(--colorPrimaryDark)">{{ ticket.get_app_display }}</h6>
			</div>
			<div class="row mt-3 text-center">
				<div class="col-4 center">
					<p><b>Type:</b> {{ ticket.get_type_display }}</p>
				</div>
				<div class="col-4 center">
					<p><b>Priority:</b> {{ ticket.get_priority_display }}</p>
				</div>
				<div class="col-4 center">
					<p><b>Status:</b> <span style="color: {{ ticket.get_status_colour }}">{{ ticket.get_status_display }}</span></p>
				</div>
			</div>
			<div class="mx-2 mb-4 mt-2">
				<p style="white-space:pre-wrap">{{ ticket.description }}</p>
			</div>
		</div>
		
		<div class="col-3 border container-fluid small">
			<div class="row border-bottom my-3">
				<div class="container">
					<div class="float-left"><p><b>Created by:</b></p></div>
					<div class="float-right"><p>{{ ticket.reporter }}</p></div>
					<div class="clearfix"></div>
					
					<div class="float-left"><p><b>Last updated by:</b></p></div>
					<div class="float-right"><p>{{ ticket.last_updater }}</p></div>
					<div class="clearfix"></div>
					
					<div class="float-left"><p><b>{% if ticket.assignee %}Assigned to:{% else %}Unassigned{% endif %}</b></p></div>
					<div class="float-right">
						{% if ticket.assignee %}<p>{{ ticket.assignee }}{% endif %}
						{% if request.user.is_staff %}
							{% include 'utils/buttons/edit.html' with css_class='edit-ticket-button' height=16 width=16 onclick="getModal('modal_assign_ticket')" tooltip_text='Assign ticket' %}
						{% endif %}
						{% if ticket.assignee %}</p>{% endif %}
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="row my-3">
				<div class="container">
					<div class="float-left"><p><b>Created on:</b></p></div>
					<div class="float-right"><p>{{ ticket.created_date }}</p></div>
					<div class="clearfix"></div>
					
					<div class="float-left"><p><b>Last updated on:</b></p></div>
					<div class="float-right"><p>{{ ticket.last_updated_date }}</p></div>
					<div class="clearfix"></div>
					
					{% if ticket.closed_date %}
						<div class="float-left"><p><b>Closed on:</b></p></div>
						<div class="float-right"><p>{{ ticket.closed_date }}</p></div>
						<div class="clearfix"></div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<ul class="nav nav-tabs mt-3" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" id="id_nav_tab_comments" data-toggle="tab" href="#id_tab_comments" role="tab" aria-controls="id_tab_comments" aria-selected="true">Comments</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="id_nav_tab_attachments" data-toggle="tab" href="#id_tab_attachments" role="tab" aria-controls="id_tab_attachments" aria-selected="false">Attachments</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="id_nav_tab_history" data-toggle="tab" href="#id_tab_history" role="tab" aria-controls="id_tab_history" aria-selected="false">History</a>
		</li>
	</ul>
	
	<div class="tab-content ticket-tab-content shadow px-3 py-3">
		<div id="id_tab_comments" class="tab-pane fade show active" role="tabpanel" aria-labelledby="id_nav_tab_comments">
			{% if ticket.comments.all %}
				<div class="small">
					{% for comment in ticket.comments.all %}
						<div class="comment shadow mb-2">
							<div class="comment-header">
								<div class="float-left">
									<b>{{ comment.creator }}</b>
									{% if comment.attachments.count %}
										added {% if comment.attachments.count == 1%} an attachment{% else %} {{ comment.attachments.count }} attachments{% endif %} and
									{% endif%} commented on {{ comment.added_date }}{% if comment.is_edited %} (edited){% endif %}
								</div>
								<div class="float-right">
									{% if request.user == comment.creator %}
										{% include 'utils/buttons/edit.html' with css_class='edit-ticket-button' height=14 width=14 onclick="getModal('modal_edit_comment', 'id="|addstr:comment.id|addstr:"')" %}
									{% endif %}
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="comment-body pt-2 pb-1">
								<p style="white-space:pre-wrap">{{ comment.text }}</p>
							</div>
						</div>
					{% endfor %}
				</div>
			{% endif %}
			<form method="POST" class="mt-3">
				{% csrf_token %}
				{{ comment_form|crispy }}
				<button type="submit" class="btn btn-primary" name="add_comment">Add comment</button>
			</form>
		</div>
		
		<div id="id_tab_attachments" class="tab-pane fade" role="tabpanel" aria-labelledby="id_nav_tab_attachments">
			{% if ticket.attachments.count %}
				<table class="table table-sm table-bordered" style="max-width:30%">
					<thead>
						<tr>
							<th>File</th>
							<th>Date uploaded</th>
						</tr>
					</thead>
					<tbody>
						{% for attachment in ticket.attachments.all %}
							<tr>
								<td><a href="{{ attachment.file.url }}" target="_blank">{{ attachment }}</a></td>
								<td>{{ attachment.uploaded_date }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			{% endif %}
			<form method="POST" class="mt-3" enctype="multipart/form-data">
				{% csrf_token %}
				{{ attachment_form|crispy }}
				{{ comment_form|crispy }}
				<button type="submit" class="btn btn-primary" name="add_attachment">Add attachment</button>
			</form>
		</div>
		
		<div id="id_tab_history" class="tab-pane fade" role="tabpanel" aria-labelledby="id_nav_tab_history">
			<div class="small">
				{% for action in ticket.actions.all %}
					<div class="comment shadow mb-2">
						<div class="comment-header">{{ action.as_html|safe }} on {{ action.timestamp }}</div>
						<div class="comment-body pt-2 pb-1">
							{% if action.is_creation %}
								{% if action.changes.count == 1 %}
									{{ action.changes.first.new_value }}
								{% else %}
									{% for change in action.changes.all %}
										<div class="row">
											<div class="col">{{ change.get_field_name }}</div>
											<div class="col">{{ change.get_new_value_display|default:'-' }}</div>
										</div>
									{% endfor %}
								{% endif %}
							{% else %}
								<div class="row">
									<div class="col"><b>Field</b></div>
									<div class="col"><b>Original Value</b></div>
									<div class="col"><b>New Value</b></div>
								</div>
								{% for change in action.changes.all %}
									<div class="row">
										<div class="col">{{ change.get_field_name }}</div>
										<div class="col">{{ change.get_old_value_display|default:'-' }}</div>
										<div class="col">{{ change.get_new_value_display|default:'-' }}</div>
									</div>
								{% endfor %}
							{% endif %}
							<p style="white-space:pre-wrap"></p>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

lions_den/templates/ticket_system/ticket_list.html
{% extends "ticket_system/base.html" %}

{% block content %}
	<div class="page-header">
		<h2 class="title pr-2" style="display:inline-block">Tickets</h2>
	</div>
	
	<div class="input-group mb-3" style="width:30%">
		<input id="id_search_text" type="search" class="textinput form-control" style="width:20%; display:inline" placeholder="Search" onsearch="filterTicketList();"/>
		<div class="input-group-append">
			{% include 'utils/buttons/search.html' with size=20 css_class='btn btn-primary search-btn' onclick='filterTicketList()' %}
		</div>
	</div>
	
	<div id="ticket_list_filters" class="mb-3">
		{% include 'ticket_system/ticket_list_filter_field.html' with field_enum=ticket_model.App name='app' default_label='All Apps'  %}
		{% include 'ticket_system/ticket_list_filter_field.html' with field_enum=ticket_model.Priority name='priority' default_label='All Priorities' %}
		{% include 'ticket_system/ticket_list_filter_field.html' with field_enum=ticket_model.Status name='status' default_label='All Statuses' %}
		
		<select name="creator" id="id_select_creator" class="select form-control">
			<option selected value>Reported by anyone</option>
			<option value="1">Reported by me</option>
		</select>
		
		<select name="watcher" id="id_select_watcher" class="select form-control">
			<option selected value>Watched by anyone</option>
			<option value="1">Watched by me</option>
		</select>
		
		{% if request.user.is_staff %}
			<select name="assignee" id="id_select_assignee" class="select form-control">
				<option selected value>Assigned to anyone</option>
				<option value="1">Assigned to me</option>
			</select>
		{% endif %}
		
		{% include 'utils/buttons/filter.html' with css_class='ml-2' onclick="clearTicketFilters()" stroke='var(--colorForeground)' tooltip_text="Clear filters" id="id_ticket_list_clear_filters_button" %}
		
	</div>
	
	{% include 'ticket_system/ticket_list_table.html' %}
{% endblock %}

lions_den/templates/ticket_system/ticket_list_filter_field.html
<select name="{{ name }}" id="id_select_{{ name }}" class="select form-control">
	<option selected value>{{ default_label }}</option>
	{% for value, label in field_enum.choices %}
		<option value="{{ value }}">{{ label }}</option>
	{% endfor %}
</select>

lions_den/templates/ticket_system/ticket_list_table.html
<div id="id_ticket_search_result">
	{% if tickets.count > 0 %}
		<table class="table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Title</th>
					<th>App</th>
					<th>Priority</th>
					<th>Status</th>
					<th>Created on</th>
					<th>Last Updated on</th>
				</tr>
			</thead>
			<tbody>
				{% for ticket in tickets %}
					<tr>
						<td>{{ ticket.id }}</td>
						<td><a href="{% url 'ticket_page' pk=ticket.id %}">{{ ticket.title }}</a></td>
						<td>{{ ticket.get_app_display }}</td>
						<td>{{ ticket.get_priority_display }}</td>
						<td>{{ ticket.get_status_display }}</td>
						<td>{{ ticket.created_date }}</td>
						<td>{{ ticket.last_updated_date }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<div class="container">
			<p>No tickets found, please refine your search</p>
		</div>
	{% endif %}
</div>